### ISSUE TITLE
Ads cannot be created in ads-form unless you add the ads structure in Mongo

### ISSUE THREAD

**Issue by rmartinezduque** [frontity/ads-form#37]
Ads cannot be created in https://ads-form.frontity.io unless you add the root structure `"ads" : { "settings" : {}, "fills" : [] }, "slots" : []` in Mongo before, copy it and paste it in Graphcool.

**Comment by luisherranz** [comment]
We're going to add this manually to Mongo when adding the other stuff (like logo, etc).
