### ISSUE TITLE
Change sign-up page styles

### ISSUE THREAD

**Issue by DAreRodz** [frontity/ads-form#44]
Child of #39

**Comment by luisherranz** [comment]
In my opinion styling this shouldn't have any priority. Only us and AZ is going to use it and this first work of styling should be focused only on UI clarity and not on aesthetics. We can do another aesthetics work afterwards if needed.

cc: @poliuk

**Comment by luisherranz** [comment]
Discussion in here: https://github.com/frontity/ads-form/pull/47
