### ISSUE TITLE
Change site list styles

### ISSUE THREAD

**Issue by DAreRodz** [frontity/ads-form#45]
Child of #39

**Comment by luisherranz** [comment]
In my opinion styling this shouldn't have any priority. Only us and AZ is going to use it and this first work of styling should be focused only on UI clarity and not on aesthetics. We can do another aesthetics work afterwards if needed.

cc: @poliuk

**Comment by Poliuk** [comment]
I repeat what I just said in https://github.com/frontity/ads-form/issues/43#issuecomment-425366057 I really think is important to deliver something better than a plain HTML.
