### ISSUE TITLE
[10] Malfunction in ads placements after changing their order or deleting them

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/ads-form#54]
When you change the order of an ad in the ads-form, it misconfigures its placements and the ones of the next ad in the list too. 

Apart from that, if an ad has more than one placement, if you delete the first one, it changes the rest of them.

Size: **(0.2)**
Environment: **production (x5)**
Range: **low (x1)**
Behaviour: **not-nice (x1)**
Mass: **everyone (x5)**
PRIORITY: **[5]**

**Comment by luisherranz** [comment]
@SantosGuillamot could you please try rating this bug with the info provided here?
https://github.com/frontity/frontity/issues/115

This is an example of a rated bug:
https://github.com/frontity/wp-plugin/issues/29

If something doesn't make sense please let me know.

**Comment by luisherranz** [comment]
@DAreRodz is this deployed?
