### ISSUE TITLE
[106] Add extra slots for placing ads

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/ads-form#62]
The customer would like to add ads in the following placements:

- Before navbar (optional for every type of view)
- After comments
- After "Next posts"
- After "More in category 1"

Maybe we could add also a placement right after the header just in case someone needs it

----

https://frontity.pipedrive.com/deal/153
Site pageviews: **(0.78)**
Extra group sites: **(0)**
Extra group pageviews: **(0)**
Development size: **(3)**
Blocking: **no frontity without it (x10)**
Environment: **integration is finishing (x10)**
Reusability potential: **marginal (x2)**
PRIORITY: **[106]**

**Comment by DAreRodz** [comment]
Start worrying about adding new slots on demand.

I think we could define a complete slot map for [frontity/saturn-theme](https://github.com/frontity/saturn-theme), covering most use cases, and document it extensively in the [frontity docs](https://support.frontity.com/integrations/ads).

Any thoughts, @luisherranz, @orballo?

**Comment by luisherranz** [comment]
Good idea. It could include images to show the positions and the same info should be available in the Saturn readme file.
